Rework Phase 3 Curriculum pages
emergentworks/curriculum pull request #84
Opened 2023-04-06 15:11 UTC by mikecargal

Aligning Phase 3 curriculum with goal of working through The Odin Project Full Stack JavaScript path.

Adding template repositories and project plans to assist tracking.

2023-04-07 02:01 UTC, ashley requested changes
Some minor requests, but overall, the workflow and project setup lgtm.

2023-04-07 10:15 UTC, mikecargal commented on docs/Phase-3/phase-3.md
I need to remove mention of modules. I thought I had gotten them, but that’s probably why I needed to step back and look at it with fresh eyes after a couple of days.

2023-04-07 10:15 UTC, mikecargal commented on docs/Phase-3/project-workflow.md
> +This project workflow is designed to assist in tracking progress through The Odin Project's JavaScrip course,
Details, details…

2023-04-07 10:16 UTC, mikecargal commented on docs/Phase-3/repository-and-project-setup.md
> +  <br/><img srcset="/curriculum/assets/images/CopyProject1.png 2x">
Ah, I always do it from the projects list, but this is probably less error prone.  TBH, I don’t think I had even noticed the option on that menu 🙄

2023-04-08 12:44 UTC, mikecargal commented
I just noticed that I need to rework the “Learning Topics” on the Summary page for Phase 3.  (It just has the JavaScript course).  I’ll rework that before as well

2023-04-08 21:01 UTC, mikecargal commented
OK, I've taken care of your comments (thanks!), and I've fleshed out the summary page to reflect the full Full Stack JavaScript path in TOP.  I think it's ready to merge.

(I've only fleshed out repo templates and projects for the first two courses.  I'll just need to stay a step ahead of mentees, but I REALLY don't see any making it through the first two course in 12 weeks.... If I'm wrong, I'll gladly scramble to flesh out those items)

2023-04-10 14:05 UTC, ashley approved these changes

2023-04-10 14:15 UTC, merged